name: ci-test-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Pega os dados que vão subir e baixam os arquivos no ubuntu
      - uses: actions/setup-go@v2 # Prepara o ambiente para o GO
        with:
          go-version: 1.15 # Parâmetro para a action setup-go@v2, informando a versão do GO
      - run: go test
      - run: go run math.go
      - name: Set up QEMU # Setup para o docker funcionar em várias arquiteturas
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx # Setup para o docker realizar o Build
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub # Faz o build da imagem
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true # Realiza o push no DockerHub
          tags: brunosana/app:latest # Nome e tag da imagem no DockerHub. Na máquina temporária, vamos ter uma imagem com esse nome